services:
  db:
    image: postgres:16
    container_name: mytodo-db-container
    environment:
      POSTGRES_DB: mytodo
      POSTGRES_USER: mytodo
      POSTGRES_PASSWORD: mytodo
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: mytodo-backend:v0.2.0
    container_name: mytodo-backend-container
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg://mytodo:mytodo@db:5432/mytodo
      FRONTEND_ORIGINS: https://mytodo.jonathanabebe.dev

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_BASE_URL: https://api.mytodo.jonathanabebe.dev
    image: mytodo-frontend:v0.2.0
    container_name: mytodo-frontend-container
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
