FROM node:22-alpine AS build

WORKDIR /app

COPY mytodo/clients/web/package*.json ./

RUN npm install

ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

COPY mytodo/clients/web ./

RUN npm run build

FROM caddy:2-alpine

COPY --from=build /app/dist /srv/frontend
