FROM node:22-alpine

WORKDIR /app

COPY mytodo/clients/web/package*.json ./
RUN npm install

COPY mytodo/clients/web ./

ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

RUN npm run build

CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "5173"]
